<a href="https://colab.research.google.com/github/Peter-obi/protein-structure-prediction-from-scratch/blob/main/Pytorch_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
from torch import math

In [2]:
x = torch.empty(3, 4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[3.2314e-18, 6.0397e-07, 1.3475e+37, 4.4605e-41],
        [3.2656e+03, 4.4605e-41, 3.6013e-43, 0.0000e+00],
        [1.2872e-04, 0.0000e+00, 1.0154e+36, 4.4606e-41]])


In [3]:
zeros = torch.zeros(2, 3)
print(zeros)

ones = torch.ones(2, 3)
print(ones)

torch.manual_seed(42)
random = torch.rand(2,3)
print(random)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [4]:
x = torch.empty(2, 3, 3)
print (x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 3, 3])
tensor([[[3.5204e-04, 0.0000e+00, 1.7521e-04],
         [0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 1.4013e-45]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 6.8664e-44],
         [0.0000e+00, 3.5226e-04, 0.0000e+00]]])
torch.Size([2, 3, 3])
tensor([[[0.0000e+00, 0.0000e+00, 1.7510e-04],
         [0.0000e+00, 3.6676e-05, 0.0000e+00],
         [3.2962e+03, 4.4605e-41, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]]])
torch.Size([2, 3, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 3, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 3, 3])
tensor([[[0.2566, 0.7936, 0.9408],

In [5]:
some_constants = torch.tensor([[3.14, 2.56], [6.52, 4.53]])
print(some_constants)

some_integers = torch.tensor((1, 2, 3, 4, 5, 6, 7, 8))
print(some_integers)

more_integers = torch.tensor(((1, 2, 3), [4, 5, 6]))
print(more_integers)

tensor([[3.1400, 2.5600],
        [6.5200, 4.5300]])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [6]:
a = torch.ones((2, 3), dtype = torch.int16)
print(a)

b = torch.rand((2, 3), dtype=torch.float64) * 20
print(b)

c = b.to(torch.int32)
print(c)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[16.8504, 17.4100,  7.5507],
        [12.2487,  1.7622, 14.0236]], dtype=torch.float64)
tensor([[16, 17,  7],
        [12,  1, 14]], dtype=torch.int32)


##Math and Logic

In [7]:
ones = torch.zeros(2, 2) + 1
print(ones)

twos = torch.ones(2, 2) * 2
print(twos)

threes = (torch.ones(2, 2) * 7 - 1)/2
print(threes)

fours = twos**2
print(fours)

sqrt2s = twos**0.5
print(sqrt2s)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


In [8]:
powers2 = twos ** torch.tensor([[1,2], [3, 4]])
print(powers2)

fives = ones + fours
print(fives)

dozens = threes * fours
print(dozens)

tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[5., 5.],
        [5., 5.]])
tensor([[12., 12.],
        [12., 12.]])


In [10]:
a = torch.rand(2, 3)
b = torch.rand(3, 2)

print(a * b) #cannot operate on tensors of different shape this way

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [11]:
a = torch.rand(2, 4) * 2 - 1
print('Common functions:')
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))

Common functions:
tensor([[0.5078, 0.6095, 0.9899, 0.3864],
        [0.7670, 0.8205, 0.2880, 0.4142]])
tensor([[1., -0., -0., -0.],
        [-0., 1., 1., 1.]])
tensor([[ 0., -1., -1., -1.],
        [-1.,  0.,  0.,  0.]])
tensor([[ 0.5000, -0.5000, -0.5000, -0.3864],
        [-0.5000,  0.5000,  0.2880,  0.4142]])


In [12]:
angles = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
sines = torch.sin(angles)
inverses = torch.asin(angles)
print('\nSine and arcsine:')
print(angles)
print(sines)
print(inverses)


Sine and arcsine:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.9033,    nan,    nan])


In [13]:
#bitwise operations
print('Bitwise Operations')
b = torch.tensor([1, 5, 11])
c = torch.tensor([2, 7, 10])
print(torch.bitwise_xor(b, c))

Bitwise Operations
tensor([3, 2, 1])


In [14]:
print('Broadcasted element-wise equality comparison:')
d = torch.tensor([[1., 2.], [3., 4.]])
e = torch.ones(1, 2) #many comparison ops support broadcasting
print(torch.eq(d, e)) #returns a tensor of type bool

Broadcasted element-wise equality comparison:
tensor([[ True, False],
        [False, False]])


In [15]:
print('Reduction ops:')
print(torch.max(d)) #returns a single element tensor ie max
print(torch.max(d).item()) #extracts the value of the returned tensor
print(torch.mean(d))
print(torch.std(d))
print(torch.prod(d))
print(torch.unique(torch.tensor([1, 2, 1, 2, 1, 2]))) #filter unique elements

Reduction ops:
tensor(4.)
4.0
tensor(2.5000)
tensor(1.2910)
tensor(24.)
tensor([1, 2])


In [16]:
#vector and linear algebra operations
v1 = torch.tensor([1., 0., 0.]) #x unit vector
v2 = torch.tensor([0., 1., 0.]) #y unit vector
m1 = torch.rand(2, 2) #random matrix
m2 = torch.tensor([[3., 0.], [0., 3.]]) #three times identity matrix
print('\nVectors and Matrices:')
print(torch.linalg.cross(v2, v1)) #negative of z unit vector(v1 x v2 == -v2 x v1)
print(m1)
m3 = torch.linalg.matmul(m1, m2)
print(m3)
print(torch.linalg.svd(m3))


Vectors and Matrices:
tensor([ 0.,  0., -1.])
tensor([[0.6581, 0.4913],
        [0.8913, 0.1447]])
tensor([[1.9744, 1.4739],
        [2.6739, 0.4342]])
torch.return_types.linalg_svd(
U=tensor([[-0.6684, -0.7438],
        [-0.7438,  0.6684]]),
S=tensor([3.5578, 0.8668]),
Vh=tensor([[-0.9299, -0.3677],
        [ 0.3677, -0.9299]]))


##Broadcasting
Each tensor must have at least one dimension - no empty tensors.

Comparing the dimension sizes of the two tensors, going from last to first:

1. Each dimension must be equal, or

2. One of the dimensions must be of size 1, or

3. The dimension does not exist in one of the tensors

In [17]:
a = torch.ones(4, 3, 2)
print(a.shape)

b = a * torch.rand(  3, 2)
print(b.shape)

c = a * torch.rand(  3, 1)
print(c.shape)

d = a * torch.rand( 1, 2) #all work because dimensions match up or 1
print(d.shape)

torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])


In [18]:
a = torch.ones(2, 4)
print(a)

b = torch.ones(2, 1)* 2
print(b)

c = a * b
print(c)
print(c.shape)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[2.],
        [2.]])
tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.]])
torch.Size([2, 4])


##Altering Tensors in place
1. Math Operators - use an '_'. Note these in-place arithmetic functions are methods on the torch.Tensor object, not attached to the torch module like many other functions (e.g., torch.sin()). As you can see from a.add_(b), the calling tensor is the one that gets changed in place.
2. Use the out argument

In [19]:
a = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 2, 3 * math.pi / 4 ])
print('a:')
print(a)
print(torch.sin(a)) #new operation in memory
print(a) #a unchanged

a:
tensor([0.0000, 0.7854, 1.5708, 4.7124, 2.3562])
tensor([ 0.0000,  0.7071,  1.0000, -1.0000,  0.7071])
tensor([0.0000, 0.7854, 1.5708, 4.7124, 2.3562])


In [20]:
b = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 2, 3 * math.pi / 4 ])
print('b:')
print(b)
print(torch.sin_(b)) #underscore maxxing
print(b) #b changed

b:
tensor([0.0000, 0.7854, 1.5708, 4.7124, 2.3562])
tensor([ 0.0000,  0.7071,  1.0000, -1.0000,  0.7071])
tensor([ 0.0000,  0.7071,  1.0000, -1.0000,  0.7071])


In [21]:
a = torch.ones(2, 2)
b = torch.ones(2, 2)

print('Before')
print(a)
print(b)
print('\nAfter adding:')
print(a.add_(b))
print(a)
print(b)
print('\nAfter multiplying:')
print(b.mul_(b))
print(b)

Before
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])

After adding:
tensor([[2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[1., 1.],
        [1., 1.]])

After multiplying:
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])


In [22]:
a = torch.rand(2, 2)
b = torch.rand(2, 2)
c = torch.rand(2, 2)
old_id = id(c)
print(old_id)

print(c)
d = torch.matmul(a, b, out = c)
print(c)

assert c is d
assert id(c) == old_id

torch.rand(2, 2, out  = c) #works for creation
print(c)
assert id(c) == old_id

136714264958272
tensor([[0.9155, 0.2418],
        [0.1591, 0.7653]])
tensor([[0.7618, 0.7753],
        [0.0124, 0.0171]])
tensor([[0.2979, 0.8035],
        [0.3813, 0.7860]])


##Copying tensors
 Assigning a tensor to a variable makes the variable a label of the tensor, and does not copy it. If you want a separate copy of the data to work on, use clone() method.  

In [23]:
a = torch.ones(2, 2)
b = a

a[0][1] = 561 # change a
print(b) #b is altered

tensor([[  1., 561.],
        [  1.,   1.]])


In [24]:
a = torch.ones(2, 2)
b = a.clone()

assert b is not a #different objects in memory
print(torch.eq(a, b)) #same contents

a[0][1] = 561
print(a) #a changes
print(b) #b remains same

tensor([[True, True],
        [True, True]])
tensor([[  1., 561.],
        [  1.,   1.]])
tensor([[1., 1.],
        [1., 1.]])


In [25]:
#to prevent clone from tracking gradients, use 'detach()'

a = torch.rand(2, 2, requires_grad=True) #turn on autograd
print(a)

b = a.clone()
print(b)

c = a.detach().clone()
print(c)

print(a)

tensor([[0.1115, 0.2477],
        [0.6524, 0.6057]], requires_grad=True)
tensor([[0.1115, 0.2477],
        [0.6524, 0.6057]], grad_fn=<CloneBackward0>)
tensor([[0.1115, 0.2477],
        [0.6524, 0.6057]])
tensor([[0.1115, 0.2477],
        [0.6524, 0.6057]], requires_grad=True)


##Moving to Accelerator

In [26]:
if torch.accelerator.is_available():
  print('We have an accelerator!')
else:
  print('Sorry, you are GPU poor')

We have an accelerator!


In [27]:
if torch.accelerator.is_available():
  gpu_rand = torch.rand(2,2, device = torch.accelerator.current_accelerator())
  print(gpu_rand)
else:
  print('Sorry, you are GPU poor')

tensor([[0.6130, 0.0101],
        [0.3984, 0.0403]], device='cuda:0')


In [28]:
my_device = torch.accelerator.current_accelerator() if torch.accelerator.is_available() else torch.device('cpu')
print('Device is {}'.format(my_device))

x = torch.rand(2,2, device=my_device)
print(x)

Device is cuda
tensor([[0.9877, 0.1289],
        [0.5621, 0.5221]], device='cuda:0')


In [30]:
#can move to another device, using 'to'
y = torch.rand(2, 2)
y = y.to(my_device)

In [31]:
#all tensors must be on same device
x = torch.rand(2, 2)
y = torch.rand(2, 2, device = 'cuda')
z = x + y #throw exception

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

##Manipulating tensor shapes
- Use unsqueeze and squeeze to change dimensions

In [32]:
a = torch.rand(3, 226, 226)
b = a.unsqueeze(0) #add a new zeroth dimension

print(a.shape)
print(b.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


In [2]:
#squeeze and unsequeeze take advantage of the fact that any dimension of extent 1 does not change the number of elements in a tensor
a = torch.rand(1, 20)
print(a.shape)
print(a)

b = a.squeeze(0)
print(b.shape) #now one dimension, one square bracket lost
print(b)

c = torch.rand(2, 2)
print(c.shape)

d = c.squeeze(0) #cant squeeze any dimension more than one
print(d.shape)

torch.Size([1, 20])
tensor([[0.8248, 0.7804, 0.7595, 0.1291, 0.3807, 0.3984, 0.2111, 0.6304, 0.3906,
         0.0444, 0.3414, 0.2031, 0.1829, 0.1677, 0.7704, 0.4353, 0.0101, 0.4081,
         0.9399, 0.3540]])
torch.Size([20])
tensor([0.8248, 0.7804, 0.7595, 0.1291, 0.3807, 0.3984, 0.2111, 0.6304, 0.3906,
        0.0444, 0.3414, 0.2031, 0.1829, 0.1677, 0.7704, 0.4353, 0.0101, 0.4081,
        0.9399, 0.3540])
torch.Size([2, 2])
torch.Size([2, 2])


In [4]:
a = torch.ones(4, 3, 2)
b = torch.rand( 3)
c = b.unsqueeze(1)
print(c.shape)
print(a * c)

torch.Size([3, 1])
tensor([[[0.3054, 0.3054],
         [0.9266, 0.9266],
         [0.1378, 0.1378]],

        [[0.3054, 0.3054],
         [0.9266, 0.9266],
         [0.1378, 0.1378]],

        [[0.3054, 0.3054],
         [0.9266, 0.9266],
         [0.1378, 0.1378]],

        [[0.3054, 0.3054],
         [0.9266, 0.9266],
         [0.1378, 0.1378]]])


In [3]:
#has in place method, using '_'
batch_me = torch.rand(3, 226, 226)
print(batch_me.shape)
batch_me.unsqueeze_(0)
print(batch_me.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


In [4]:
output_3d = torch.rand(6, 20, 20)
print(output_3d.shape)

input1d = output_3d.reshape(6 * 20 * 20) #move from 3D to 1D. remmeber reshape shares same underlying memory, so clone if you need to remain same
print(input1d.shape)

input1d = output_3d.reshape(-1) #does same job
print(input1d.shape)

print(torch.reshape(output_3d, (6 * 20 * 20,)).shape)

torch.Size([6, 20, 20])
torch.Size([2400])
torch.Size([2400])


##Numpy bridge

In [5]:
import numpy as np

numpy_array = np.ones((2, 3))
print(numpy_array)

pytorch_tensor = torch.from_numpy(numpy_array)
print(pytorch_tensor)

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [6]:
pytorch_rand = torch.rand(2, 3)
print(pytorch_rand)

numpy_rand = pytorch_rand.numpy()
print(numpy_rand)

tensor([[0.3081, 0.6899, 0.0697],
        [0.1185, 0.6618, 0.2547]])
[[0.30811113 0.6899126  0.06968129]
 [0.11846095 0.6617776  0.25474173]]


In [9]:
#change to one affects the other
numpy_array[1, 1] = 13
print(pytorch_tensor)

pytorch_rand[1, 1] = 17
print(numpy_rand)

tensor([[ 1.,  1.,  1.],
        [ 1., 13.,  1.]], dtype=torch.float64)
[[ 0.30811113  0.6899126   0.06968129]
 [ 0.11846095 17.          0.25474173]]
