<a href="https://colab.research.google.com/github/Peter-obi/protein-structure-prediction-from-scratch/blob/main/Pytorch_building_models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
from torch import nn

In [2]:
class TinyModel(nn.Module):

  def __init__(self):
    super(TinyModel, self).__init__()

    self.linear1 = nn.Linear(100, 200)
    self.activation = nn.ReLU()
    self.linear2 = nn.Linear(200, 10)
    self.softmax = nn.Softmax()

  def forward(self, x):
    x = self.linear1(x)
    x = self.activation(x)
    x = self.linear2(x)
    x = self.softmax(x)
    return x

tinymodel = TinyModel()

print('The Model')
print(tinymodel)

print('\n\nJust one layer:')
print(tinymodel.linear2)

print('\n\nModel params:')
for params in tinymodel.parameters():
  print(params)

print('\n\nLayer params:')
for params in tinymodel.linear2.parameters():
  print(params)

The Model
TinyModel(
  (linear1): Linear(in_features=100, out_features=200, bias=True)
  (activation): ReLU()
  (linear2): Linear(in_features=200, out_features=10, bias=True)
  (softmax): Softmax(dim=None)
)


Just one layer:
Linear(in_features=200, out_features=10, bias=True)


Model params:
Parameter containing:
tensor([[-0.0211, -0.0102, -0.0075,  ..., -0.0109, -0.0614, -0.0344],
        [ 0.0350,  0.0118, -0.0243,  ..., -0.0956,  0.0264, -0.0084],
        [-0.0333, -0.0483, -0.0951,  ..., -0.0419,  0.0713,  0.0800],
        ...,
        [-0.0763, -0.0199, -0.0464,  ..., -0.0509,  0.0826, -0.0525],
        [ 0.0015,  0.0134,  0.0997,  ...,  0.0191, -0.0607,  0.0672],
        [ 0.0191,  0.0152,  0.0434,  ..., -0.0148,  0.0624, -0.0923]],
       requires_grad=True)
Parameter containing:
tensor([ 0.0970,  0.0055,  0.0021, -0.0122,  0.0728, -0.0259, -0.0649,  0.0939,
        -0.0282, -0.0459, -0.0978,  0.0874, -0.0855, -0.0725, -0.0211,  0.0754,
        -0.0372, -0.0453, -0.0860,  0.052

In [3]:
lin = torch.nn.Linear(3, 2)
x = torch.rand(1, 3)
print('Input:')
print(x)

print('\n\nWeight and Bias parameters:')
for param in lin.parameters():
  print(param)

y = lin(x)
print('\n\nOutput:')
print(y)

Input:
tensor([[0.0831, 0.0336, 0.1012]])


Weight and Bias parameters:
Parameter containing:
tensor([[ 0.1753,  0.4416, -0.0654],
        [ 0.2104, -0.4030,  0.1514]], requires_grad=True)
Parameter containing:
tensor([-0.5199,  0.4126], requires_grad=True)


Output:
tensor([[-0.4971,  0.4319]], grad_fn=<AddmmBackward0>)


In [4]:
import torch.nn.functional as F

class LeNet(nn.Module):
  def __init__(self):
    super(LeNet, self).__init__()
    #1x32x32 input image channel (black & white), 6 output channels, 5x5 convolution kernel
    self.conv1 = nn.Conv2d(1, 6, 5)
    self.conv2 = nn.Conv2d(6, 16, 3)
    #an affine operation: y = Wx + b
    self.fc1 = nn.Linear(16 * 6 * 6, 120) #6 * 6 from image dimension
    self.fc2 = nn.Linear(120, 84)
    self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
      #Max pooling over a (2, 2) window
      x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
      #if the size is a square you can only specify a single number
      x = F.max_pool2d(F.relu(self.conv2(x)), 2)
      x = x.view(-1, self.num_flat_features(x))
      x = F.relu(self.fc1(x))
      x = F.relu(self.fc2(x))
      x = self.fc3(x)
      return x

    def num_flat_features(self, x):
      size = x.size()[1:] #all dimensions except the batch dimension
      num_features = 1
      for s in size:
        num_features *=s
        return num_features