<a href="https://colab.research.google.com/github/Peter-obi/protein-structure-prediction-from-scratch/blob/main/Pytorch_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
x = torch.empty(3, 4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[2.7491e+20, 6.1949e-04, 1.9421e+31, 2.7491e+20],
        [2.3078e-12, 7.1760e+22, 7.2250e+28, 1.5766e-19],
        [1.7584e-04, 1.7298e-04, 1.6967e-07, 2.0914e+20]])


In [3]:
zeros = torch.zeros(2, 3)
print(zeros)

ones = torch.ones(2, 3)
print(ones)

torch.manual_seed(42)
random = torch.rand(2,3)
print(random)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [4]:
x = torch.empty(2, 3, 3)
print (x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 3, 3])
tensor([[[3.7842e-12, 0.0000e+00, 0.0000e+00],
         [1.5046e-36, 3.8075e-15, 0.0000e+00],
         [1.0842e-19, 0.0000e+00, 3.8474e-12]],

        [[0.0000e+00, 3.8487e-12, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 6.8664e-44],
         [0.0000e+00, 1.9005e-12, 0.0000e+00]]])
torch.Size([2, 3, 3])
tensor([[[0.0000e+00, 0.0000e+00, 3.8482e-12],
         [0.0000e+00, 4.3235e-13, 0.0000e+00],
         [8.6456e+12, 4.3522e-41, 1.4013e-45]],

        [[0.0000e+00, 2.5223e-44, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]]])
torch.Size([2, 3, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 3, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 3, 3])
tensor([[[0.2566, 0.7936, 0.9408],

In [5]:
some_constants = torch.tensor([[3.14, 2.56], [6.52, 4.53]])
print(some_constants)

some_integers = torch.tensor((1, 2, 3, 4, 5, 6, 7, 8))
print(some_integers)

more_integers = torch.tensor(((1, 2, 3), [4, 5, 6]))
print(more_integers)

tensor([[3.1400, 2.5600],
        [6.5200, 4.5300]])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [6]:
a = torch.ones((2, 3), dtype = torch.int16)
print(a)

b = torch.rand((2, 3), dtype=torch.float64) * 20
print(b)

c = b.to(torch.int32)
print(c)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[16.8504, 17.4100,  7.5507],
        [12.2487,  1.7622, 14.0236]], dtype=torch.float64)
tensor([[16, 17,  7],
        [12,  1, 14]], dtype=torch.int32)


##Math and Logic

In [8]:
ones = torch.zeros(2, 2) + 1
print(ones)

twos = torch.ones(2, 2) * 2
print(twos)

threes = (torch.ones(2, 2) * 7 - 1)/2
print(threes)

fours = twos**2
print(fours)

sqrt2s = twos**0.5
print(sqrt2s)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


In [9]:
powers2 = twos ** torch.tensor([[1,2], [3, 4]])
print(powers2)

fives = ones + fours
print(fives)

dozens = threes * fours
print(dozens)

tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[5., 5.],
        [5., 5.]])
tensor([[12., 12.],
        [12., 12.]])


In [10]:
a = torch.rand(2, 3)
b = torch.rand(3, 2)

print(a * b) #cannot operate on tensors of different shape this way

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

##Broadcasting
Each tensor must have at least one dimension - no empty tensors.

Comparing the dimension sizes of the two tensors, going from last to first:

1. Each dimension must be equal, or

2. One of the dimensions must be of size 1, or

3. The dimension does not exist in one of the tensors

In [12]:
a = torch.ones(4, 3, 2)
print(a)

b = a * torch.rand(  3, 2)
print(b)

c = a * torch.rand(  3, 1)
print(c)

d = a * torch.rand( 1, 2) #all work because dimensions match up or 1
print(d)

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])
tensor([[[0.1447, 0.5315],
         [0.1587, 0.6542],
         [0.3278, 0.6532]],

        [[0.1447, 0.5315],
         [0.1587, 0.6542],
         [0.3278, 0.6532]],

        [[0.1447, 0.5315],
         [0.1587, 0.6542],
         [0.3278, 0.6532]],

        [[0.1447, 0.5315],
         [0.1587, 0.6542],
         [0.3278, 0.6532]]])
tensor([[[0.3958, 0.3958],
         [0.9147, 0.9147],
         [0.2036, 0.2036]],

        [[0.3958, 0.3958],
         [0.9147, 0.9147],
         [0.2036, 0.2036]],

        [[0.3958, 0.3958],
         [0.9147, 0.9147],
         [0.2036, 0.2036]],

        [[0.3958, 0.3958],
         [0.9147, 0.9147],
         [0.2036, 0.2036]]])
tensor([[[0.2018, 0.2018],
         [0.2018, 0.2018],
         [0.2018, 0.2018]],

        [[0.2018,