<a href="https://colab.research.google.com/github/Peter-obi/protein-structure-prediction-from-scratch/blob/main/Pytorch_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [3]:
x = torch.empty(3, 4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [4]:
zeros = torch.zeros(2, 3)
print(zeros)

ones = torch.ones(2, 3)
print(ones)

torch.manual_seed(42)
random = torch.rand(2,3)
print(random)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [5]:
x = torch.empty(2, 3, 3)
print (x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 3, 3])
tensor([[[0.0000e+00, 0.0000e+00, 2.7340e+20],
         [6.8589e+22, 1.5766e-19, 1.4600e-19],
         [4.8604e+30, 1.7469e+19, 3.0958e-18]],

        [[1.6869e-07, 2.9907e+21, 7.5343e+28],
         [7.7128e+31, 3.3129e-18, 1.6869e-07],
         [3.1360e+27, 1.6636e+22, 3.0555e-18]]])
torch.Size([2, 3, 3])
tensor([[[ 0.0000e+00,  0.0000e+00,  9.0217e-26],
         [ 0.0000e+00,  1.1904e-26,  0.0000e+00],
         [-2.3301e+28,  4.4260e-41,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]])
torch.Size([2, 3, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 3, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 3, 3])
tensor([[[0.2566